berty/weshnet

orbitdb.go, pkg/bertypush/push_handler.go, pkg/cryptoutil/keystore_message.go, pkg/cryptoutil/keystore_message_utils_test.go, pkg/logutil/crypto_utils.go, pkg/tyber/step.go, service.go, store_message.go, testing.go
=> fix: debug and fix lost messages

.github/workflows/ssh-runner.yml
=> fix: ssh-runner.yml github action

pkg/logutil/logger_native_darwin.go, pkg/netmanager/connectivity.go, pkg/netmanager/netmanager.go, pkg/netmanager/netmanager_test.go
=> feat: netmanager

api/protocol/protocoltypes.proto, docs/apis/protocoltypes.md, docs/apis/protocoltypes.swagger.json, pkg/protocoltypes/protocoltypes.pb.go, pkg/protocoltypes/protocoltypes_grpc.pb.go
Some clarifications to InstanceGetConfiguration and the Reply type. More updates to other methods to come later.
=> chore: InstanceGetConfiguration Proto doc: add details

.github/workflows/buf-push.yml, .tool-versions
Automatically push bug on new release
=> chore: add buf-push auto release

service_client.go
remove useless panic on grpc server close
=> fix: remove panic on grpc close error

pkg/netmanager/netmanager.go
=> fix: check if context is expired inside WaitForStageChange (netmanager)

.golangci.yml
=> chore: disable goconst in lint

pkg/netmanager/connectivity.go
=> feat: new functions that allow the parsing of connectivity info

pkg/netmanager/netmanager_noop.go
=> feat: function to create noop netmanager

pkg/ipfsutil/lifecycle.go
=> feat: Drop unavailable peer connection when network connectivity change

INSTALL.md
Instructions for bash copied from https://asdf-vm.com .
=> chore: Update INSTALL instructions for bash

service.go
=> feat: add tinder default init

service_client.go
add default logger on `Persistance` and `InMemory` client
=> feat: enable logger from env

service_client.go
quick fix for lint error that bypass ci linter
=> chore: fix lint error

group_context.go, orbitdb.go, orbitdb_many_adds_berty_test.go, orbitdb_test.go, pkg/secretstore/secret_store_messages_test.go, service_group.go, store_metadata_test.go
rework group context, make it cleaner, more readable and more logical
=> fix: rework group context

pkg/tinder/driver_localdiscovery.go, pkg/tinder/driver_localdiscovery_test.go
fix a local discovery bug where `protocol.ID("wesh/p2p/localrecord")` was register after two peers connection
=> fix:  handle `EvtPeerProtocolsUpdated` in local discovery driver

pkg/tinder/peer_cache.go
make function comment match function name
=> chore: make function comment match function name

pkg/grpcutil/simple_auth_test.go
=> chore: fix comment

pkg/secretstore/secret_store_interfaces.go
fix struct field name in comment
=> chore: fix struct field name in comment

infra/README.md
Update the infra/README to show how to use WithP2PRdvpMaddrs and WithP2PStaticRelays.
Also change the IP address in the example maddr to a public address (not LAN).
=> chore: infra/README: Show how to use WithP2PRdvpMaddrs and WithP2PStaticRelays

pkg/grpcutil/simple_auth.go
=> chore: fix struct name

.github/ISSUE_TEMPLATE/question_template.yml
=> chore: remove redundant word

blackbox_test.go, contact_request_manager.go, events.go, group_context.go, pkg/ipfsutil/pubsub_api.go, pkg/proximitytransport/transport.go, testing_test.go
=> chore: fix some typos in comment

pkg/ble-driver/BertyDevice_darwin.m, pkg/ipfsutil/lifecycle.go
fix some minor issues in the comments
=> chore: fix some minor issues in the comments

service_client.go, store_message.go
`uanble` → `unable`
`Cyphertext` → `Ciphertext `
=> chore: fix some minor issues
