group_context.go
`activateGroupContext` calls `activateGroupContextactivateGroupContext` and starts a goroutine to monitor the channel for public keys of added devices. If `selfAnnouncement` is true, then `AddDeviceToGroup` is called so that the goroutine should receive the member's own device key. `activateGroupContext` can return before the asynchronous goroutines are signalled to add the device keys. Another function like `ActivateGroup` which calls `activateGroupContext` can return before all the needed keys are added. This is a bug because `ActivateGroup` does not finish activating the group because the needed keys are not added.
This pull request updates `activateGroupContext` to add a `WaitGroup` which is signalled by the `WatchNewMembersAndSendSecrets` goroutine. If `selfAnnouncement` is true and …
=> fix: activateGroupContext: wait for the watch new members goroutine to add the device key

.github/workflows/benchmark.yml, .github/workflows/release.yml, .github/workflows/ssh-runner.yml
Enable Sementic Release to this repo in Github Action.
The `release.yml` file is from the Berty but I removed everything related to Gorealeaser because Wesnet there is not binary to compile.
=> chore: restore sementic release

INSTALL.md, README.md
This pull request adds an INSTALL file for macOS and Ubuntu to install asdf, get the code and build it. This also updates the README to point to the INSTALL file and to the web site at wesh.network .  (We change the title of the README to "Wesh Network Toolkit" to be consistent with the web site.)
=> chore: Add INSTALL.md . Update README.md to use it.

Makefile
The Makefile target `asdf.install_plugins` runs `asdf plugin add` and checks the error code. This works on macOS but not on Ubuntu which doesn't like the spaces around `==` . This pull request removes the spaces so that the check is `$$?==2` . Now it works on Ubuntu.
=> fix: In Makefile asdf.install_plugins, remove spaces in error code check

gen.sum
PR #18 changed the Makefile, but forgot to update `gen.sum`. This is the new output from 
`make regenerate` .
=> fix: Update gen.sum for changes in PR #18

.github/ISSUE_TEMPLATE/bug_template.yml, .github/ISSUE_TEMPLATE/feature_template.yml, .github/ISSUE_TEMPLATE/question_template.yml
Update the GitHub issue templates to be [like go-orbit-db](https://github.com/berty/go-orbit-db/issues/new/choose). (This was done to make it appropriate for a developer package, not an end-user app.)
=> chore: In .github/ISSUE_TEMPLATE, update templates to be like go-orbit-db

orbitdb.go
wait for the correct replicated event while loading entries in `setHeadsForGroup` . This is a follow-up to PR #12 .
=> fix: wait for the correct head entries in replicated event

account_export.go, account_export_test.go, orbitdb.go, orbitdb_many_adds_berty_test.go, service.go, store_message.go, store_metadata.go, testing.go
As part of the separation of Wesh from Berty Messenger, rename the struct BertyOrbitDB to WeshOrbitDB.
When Berty Messenger uses the new version of weshnet, it will be necessary to do the same rename, for example [in the Manager struct](https://github.com/berty/berty/blob/7c0fdaff9a86d05107d43f9fcf15e1e7a886b8ef/go/internal/initutil/manager.go#L164).
=> chore: Rename BertyOrbitDB to WeshOrbitDB

account_export_test.go, store_message_test.go, store_metadata_test.go
After recent bug fixes, some flappy tests are now passing on the CI runner with `TEST_STABILITY=flappy go test -v -race -count=25` . In `Test_AddMessage_ListMessages_manually_supplying_secrets`, we remove the flappy filter at the end of the test. In `TestFlappyRestoreAccount` and `TestFlappyMetadataRendezvousPointLifecycle`, we remove the flappy filter and rename to remove "Flappy".
For now, we do not change the remaining flappy tests: `TestFlappyMultiDevices_Basic`, `TestRaceReactivateAccountGroup` and `TestRaceReactivateContactGroup`, and the tests in scenario_test.go .
=> chore: remove testutil.Flappy filter in some tests

.tool-versions
=> chore: bump golangci-lint to 1.51.2

deactivate_test.go, pkg/cryptoutil/keystore_message.go, pkg/cryptoutil/keystore_message_utils.go, pkg/cryptoutil/keystore_message_utils_test.go
- use the first/last index value when computing push group references
- fix a bug that precomputes 100 keys each time we consume one key in the cache. Now, we precompute 100 keys only when we register a new device secret and we precompute only one key when we consume a key.
- add comments on functions
Set `TestReactivateAccountGroup` as a flappy test (the instability has no link with this PR).
=> fix: various fixes in message keystore

pkg/cryptoutil/keystore_device.go
It's not necessary to init the chain key counter to a random number.
=> chore: In NewDeviceSecret, init the chain key counter to zero

go.mod, store_message.go
To avoid out-of-order processing, don't process messages with concurrent goroutines. We only need a goroutine to signal the next message without blocking. (And now we don't need a semaphore.)
=> fix: In processMessageLoop, process the message without a goroutine

orbitdb.go
`setHeadsForGroup` [declares](https://github.com/berty/weshnet/blob/fc745c8cd65a585182065bbdcefe7d112d2474ce/orbitdb.go#L259) `id := g.GroupIDAsString()` . Then a few lines later it [declares the same value](https://github.com/berty/weshnet/blob/fc745c8cd65a585182065bbdcefe7d112d2474ce/orbitdb.go#L275) with a different variable name `groupID`. (The function `OpenGroup` does the same thing [here](https://github.com/berty/weshnet/blob/fc745c8cd65a585182065bbdcefe7d112d2474ce/orbitdb.go#L389) and [here](https://github.com/berty/weshnet/blob/fc745c8cd65a585182065bbdcefe7d112d2474ce/orbitdb.go#L399).) This is not a functionality bug but it makes the code confusing.
This pull request changes to first declaration to `groupID` and removes the second declaration.
=> fix: Only declare groupID once In setHeadsForGroup and OpenGroup

store_message.go
PR #45 changed `processMessageLoop` to not use a goroutine. After an error, it does `continue`. But we need to unlock the mutex before `continue`, similar to [another place](https://github.com/jefft0/weshnet/blob/7bab7b718d03787da18dccd326d1efa2d4def1ba/store_message.go#L190) in the same function.
This PR fixes the bug of not syncing over 100 pending messages when the receiver starts.
=> fix: In processMessageLoop, call muDeviceCaches.Unlock() before continue

.github/workflows/codeql-analysis.yml
Only run the job if github.repository_owner == 'berty' . This prevents running when a user syncs a fork.
=> chore: Don't run codeql workflow on forks

api_event.go
The same function has another variable named "sub".
=> chore: In GroupMessageList, rename the inner "sub" to avoid confusion

.github/workflows/benchmark.yml, .github/workflows/buf-push.yml, .github/workflows/dependent-issues.yml, .github/workflows/go.yml, .github/workflows/pr.yml, .github/workflows/protobuf.yml, .github/workflows/release.yml
PR #61 was successful to prevent running the codeql workflow jobs when syncing a fork. This pull request does the same for the other workflow jobs. Only run the job if github.repository_owner == 'berty' .
=> chore: Don't run workflow jobs on forks

blackbox_test.go, service_client.go
This is a low-priority pull request to fix the spelling of "persistent". It is low priority because the fix is only for internal identifiers.
=> fix: Rename persistant to persistent (spelling)

.github/workflows/benchmark.yml, .github/workflows/protobuf.yml
PR #66 was successful to prevent running the workflow jobs when syncing a fork, except where there are two `if` statements. These need to be combined into one `if` statement with `&&`.
=> chore: Fix PR #66 syntax. Don't run workflow jobs on forks

.tool-versions
Remove specific version numbers and dates in the comments because they get out of sync when we do global updates of actual version numbers. Put a comment at the top of the file explaining that the "as of" date can be seen in git blame.
=> In .tool-versions comments, remove version numbers and dates in comments

.github/workflows/benchmark.yml, .github/workflows/buf-push.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependent-issues.yml, .github/workflows/go.yml, .github/workflows/pr.yml, .github/workflows/protobuf.yml, .github/workflows/release.yml, pkg/secretstore/secret_store_messages.go.dont-encrypt
In PR #66 we added a check in all workflows so that they won't run on forks. But now GitHub has a Settings option to not run workflow actions on the fork. So the check in the workflow script is unneeded and complicating. This PR reverts those changes.
=> chore: Revert PR 66 - remove unneeded workflow owner check

api_event.go
fix potential infinity loop caused by closed channel instead of keeping it at `nil`
=> fix: event Infinity loop

account_export_test.go
TestRestoreAccount is failing on the CI for Linux (but passing on macOS and Windows). Until we have time to investigate, rename it to TestFlappyRestoreAccount and make it flappy. This partially reverts PR #30.
=> chore: Make TestRestoreAccount flappy

go.mod, go.sum, pkg/ipfsutil/mobile.go, service.go, service_client.go
This uses https://github.com/berty/go-libp2p-pubsub which weshnet will use until the main https://github.com/libp2p/go-libp2p-pubsub merges the pull request with the same fix.
=> fix: pubsub discovery

go.mod, go.sum
In berty and other repos, dependabot made PR https://github.com/berty/berty/pull/4744 to upgrade go-libp2p. For some reason, it didn't make a PR for weshnet, so this PR does the same thing.
=> chore: bump github.com/libp2p/go-libp2p from 0.27.6 to 0.27.8

INSTALL.md
In INSTALL.md, add Ubuntu 24.04. It doesn't have gcc by default, so add `build-essential` to the apt install, which fixes bug https://github.com/berty/berty/issues/4871 .
=> chore: INSTALL: Add Ubuntu 24.04 with build-essential

service.go
This PR sets the IPFS mobile repo path correctly when we create it. So we will be able to get this information in the struct later.
=> fix: set repo path correctly

README.md
Similar to PR https://github.com/berty/www.wesh.network/pull/34 on the weshnet website, update links to the buf API docs to berty-technologies .
=> chore: README: Update the buf doc link to berty-technologies

pkg/proximitytransport/conn.go, pkg/proximitytransport/listener.go, pkg/proximitytransport/transport.go
When the proximity transport was created, it took a `host.Host` as argument. But since https://github.com/libp2p/go-libp2p/pull/2118, the host argument is not more provided causing a failure on proximitytransport.
Instead of getting the host, we get the swarm to work with.
Btw, I opened a libp2p PR to update the Transport option documentation: https://github.com/libp2p/go-libp2p/pull/3144
=> fix: proximitytransport creation

pkg/outofstoremessage/outofstoremessage_test.go, pkg/outofstoremessage/service_outofstoremessage.go, service_client.go
The `Opts` for the general-purpose `NewServiceClient` now has `P2PStaticRelays` and `P2PRdvpMaddrs`. We want users of the more specific helper functions `NewInMemoryServiceClient` and `NewPersistentServiceClient` to be able to use them.
* Move the options for `OOSMOption` and related functions to the sub package `pkg/outofstoremessage` . This frees up the namespace `weshnet`
* Add `ServiceOption` and related "With" functions like `WithP2PStaticRelays`
* In `NewInMemoryServiceClient` and `NewPersistentServiceClient`, copy the supplied options to `Opts`
=> feat: Support top level service options rdvp and relay nodes

pkg/rendezvous/rotation.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
=> refactor: use the built-in max/min to simplify the code
